### ISSUE TITLE
Update build tcl scripts

### ISSUE THREAD

**Issue by gutelfuldead** [fpgadeveloper/ethernet-fmc-max-throughput#1]
Building on Linux CentOS7 with Vivado 2020.2 I had to add the `update_ip_catalog -rebuild` command to the build tcl script for it to generate the BD after adding the ip_repo_paths.

```
set_property "ip_repo_paths" "[file normalize "$origin_dir/../HLS/axi_init/proj_axi_init/solution1"] [file normalize "$origin_dir/../HLS/eth_traffic_gen/proj_eth_traffic_gen/solution1"]" $obj
update_ip_catalog -rebuild
```

**Comment by fpgadeveloper** [comment]
Thanks for sharing. I'll test this and get it into the repo.
